default:
  tenant:
    id: 8bc6ba5c-b1ed-4d67-a434-e82e940ff389
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://test-services-b.logo-paas.com:8761/eureka
idm:
  enabled: true
  authorize:
    url: http://test-services-b.logo-paas.com:5101/legacy/sts/api/oauth/authorize
  logout:
    url: http://test-services-b.logo-paas.com:5101/legacy/sts/api/account/logout
  token:
    url: http://test-services-b.logo-paas.com:5101/legacy/sts/api/oauth/token
  client:
    id: a3f0fd26-e393-4a4d-beef-81c83cb35c96
    secret: 262c618f-53de-4d5c-b527-766ab339cf3f
    version: v1.0

kafka:
  enabled: true
  bootstrap:
    servers: test-services-a.logo-paas.com:9092

lbs:
  serviceRegistration:
    enabled: false
  service:
    grc-frm:
      basePath: /
    grc-aws:
      basePath: /
    authorization:
      basePath: /v1_0/NAF.Services.Authorization.WAS
      serviceId: NAFCORESERVICESAUTHORIZATION
    cloudcontrol:
      basePath: /v1_0/NAF.Services.CloudControl.APIWebService
    idp:
      basePath: /v1_0/NAF.Services.IDP.WAS
      serviceId: NAFCORESERVICESIDM
    menu:
      basePath: /v1_0/NAF.Services.Menu.APIWebService
    tokenparser:
      basePath: /v1_0/NAF.Services.Sts.TokenParser.WAS
      serviceId: NAFCORESERVICESIDM
    securityinfo:
      basePath: /v1_0/NAF.Services.SecurityInfo.WAS
      serviceId: NAFCORESERVICESIDM
    settings:
      basePath: /
      serviceId: NAFCORESERVICESSETTINGS
    localization-service:
      basePath: /localization/v1
    messageregistry:
      basePath: /
      serviceId: NAFCORESERVICESMESSAGEREGISTRY